#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

rm log.*
rm foam.foam
rm -r constant/polyMesh
rm -r postProcessing
rm -r dynamicCode

foamListTimes -rm
