#!/bin/bash
cd ${0%/*} || exit 1

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if OpenFOAMv-2106 has been sourced
if [ "$FOAM_API" != "2106" ]; then
    echo "Error: OpenFOAM-v2106 is not sourced. Please source OpenFOAM-v2106 and try again."
    exit 0;
fi


#check if GIT_ROOT_DIR was not already set
if [ -z "$GIT_ROOT_DIR" ]; then
    echo "The local bashrc is not properly sourced. Run 'source bashrc'"
    exit 0;
fi


#check if $FOAM_USER_LIBBIN was not overwritten eg by sourcing OpenFOAM again
if [ "$SOURCE_DIR" == "$GIT_ROOT_DIR" ]; then
    if ! echo "$LD_LIBRARY_PATH" | tr ':' '\n' | grep -q "$GIT_ROOT_DIR"; then
        echo
        echo $GIT_ROOT_DIR " is not in LD_LIBRARY_PATH. Have you sourced OpenFOAM again after sourcing the bashrc?"
        echo "Use 'unsetVariables; source bashrc' or open a new terminal."
        exit 0;
    fi
    else 
        echo $SOURCE_DIR
        echo $GIT_ROOT_DIR
fi

#update git submodules if neccessary
if [ "$SOURCE_DIR" != "$GIT_ROOT_DIR" ]; then
    echo "'GIT_ROOT_DIR' is not this directory. Skipping initialization of submodules."
else 
    source $LOCAL_SCRIPT_PATH/bash/git
    updateGitSubmodules
fi


echo "Compiling multiMultiFoam..." 
$SOURCE_DIR/code/multiMultiFoam/Allwmake

echo "Compiling multiDimAMR..." 
$SOURCE_DIR/code/multiDimAMR/Allwmake

echo "Compiling twoPhaseFlow..."
$SOURCE_DIR/code/twoPhaseFlow/Allwmake.pre
wmake -j8 libso $SOURCE_DIR/code/twoPhaseFlow/code/ThirdParty/src/VoF

wmake -j8 code/src

