#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

#rm log.*
#rm -r processor*
#rm -r constant/polyMesh

foamListTimes -rm
#cp -r system/orig.0 0
