#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch foam.foam

cp -r 0.orig 0/

runApplication blockMesh

runApplication simpleFoam

postProcess -func CVforces -latestTime
