#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if OpenFOAMv-2106 has been sourced
# if [ "$FOAM_API" != "2106" ]; then
#     echo "Error: OpenFOAM-v2106 is not sourced. Please source OpenFOAM-v2106 and try again."
#     exit 0;
# fi


#check if GIT_ROOT_DIR was not already set
if [ -z "$GIT_ROOT_DIR" ]; then
    echo "The local bashrc is not properly sourced. Run 'source bashrc'"
    exit 0;
fi


#check if $FOAM_USER_LIBBIN was not overwritten eg by sourcing OpenFOAM again
if [ "$SOURCE_DIR" == "$GIT_ROOT_DIR" ]; then
    if ! echo "$LD_LIBRARY_PATH" | tr ':' '\n' | grep -q "$GIT_ROOT_DIR"; then
        echo
        echo $GIT_ROOT_DIR " is not in LD_LIBRARY_PATH. Have you sourced OpenFOAM again after sourcing the bashrc?"
        echo "Use 'unsetVariables; source bashrc' or open a new terminal."
        exit 0;
    fi
    else 
        echo $SOURCE_DIR
        echo $GIT_ROOT_DIR
fi


runApplication blockMesh

foamListTimes -rm -withZero

restore0Dir

runApplication pimpleFoam


#runApplication $FOAM_USER_APPBIN/IBMFoam

#postProcess -func sample -latestTime

#python3 scripts/postProcessing.py
