#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication ../../code/bin/multiMultiFoam

postProcess -func sample -latestTime

python3 scripts/postProcessing.py

touch foam.foam
