#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# grad(U)
simpleFoam -postProcess -func "grad(U)" -latestTime

# controlVolumeSampling
postProcess -latestTime -func controlVolumeSampling

python3 pythonScripts/controlVolumeCalculation.py

#------------------------------------------------------------------------------
